language: python
python:
  - '3.6'
sudo: false
before_install:
  - if [[ $TOX_ENV = py35 && -f ~/virtualenv/python3.5/bin/activate ]]; then source ~/virtualenv/python3.5/bin/activate; fi
env:
  - TOX_ENV=flake8
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
