language: python
python:
  - 3.6
env:
  - TOX_ENV=flake8
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=py36
install:
  - pip install --upgrade pip
  - pip install tox
script:
  - tox -e $TOX_ENV
after_success:
  coveralls
