#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""md2pdf - Markdown to PDF conversion tool.

Usage: md2pdf [options] INPUT.MD OUTPUT.PDF

Options:
    --css=STYLE.CSS
"""

import sys

from docopt import docopt

from md2pdf.core import md2pdf

__title__ = 'md2pdf'
__version__ = '0.2'
__author__ = 'Julien Maupetit'
__license__ = 'MIT'
__copyright__ = 'Copyright 2013 Julien Maupetit'


def main(argv=None):

    # Parse command line arguments
    arguments = docopt(
        __doc__,
        version='md2pdf %s' % __version__)

    # Paths
    md_file_path = arguments.get('INPUT.MD')
    pdf_file_path = arguments.get('OUTPUT.PDF')
    css_file_path = arguments.get('--css', None)

    md2pdf(md_file_path, pdf_file_path, css_file_path)

    return 1


if __name__ == '__main__':
    sys.exit(main())
